name = "EQ Scalculator"
description = "Earthquake Scaling Relationship Calculator"
packages = ["pandas", "numpy", "scipy", "plotly"]  # Added plotly

# FETCH CORE LOGIC
[[fetch]]
from = "_core"
to_folder = "_core"
files = ["generic_solver.py", "helpers.py", "__init__.py"]

# FETCH MODELS (Add all your models here)
[[fetch]]
from = "scaling_models/leonard_2014"
to_folder = "scaling_models/leonard_2014"
files = ["leonard_2014.json"]

[[fetch]]
from = "scaling_models/somerville_2014"
to_folder = "scaling_models/somerville_2014"
files = ["somerville_2014.json"]