name = "EQ Scalculator"
description = "Earthquake Scaling Relationship Calculator"
packages = ["pandas", "numpy", "scipy", "plotly"]

# --- FETCH CORE ---
[[fetch]]
from = "_core"
to_folder = "_core"
files = ["generic_solver.py", "helpers.py", "__init__.py"]

# --- FETCH MODELS (All 4 must be here) ---

[[fetch]]
from = "scaling_models/leonard_2014"
to_folder = "scaling_models/leonard_2014"
files = ["leonard_2014.json"]

[[fetch]]
from = "scaling_models/somerville_2014"
to_folder = "scaling_models/somerville_2014"
files = ["somerville_2014.json"]

[[fetch]]
from = "scaling_models/wells_coppersmith_1994"
to_folder = "scaling_models/wells_coppersmith_1994"
files = ["wells_coppersmith_1994.json"]

[[fetch]]
from = "scaling_models/yang_etal_2020"
to_folder = "scaling_models/yang_etal_2020"
files = ["yang_2020.json"]